/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.proyectofinaldb.ui;


import com.umg.proyectofinaldb.db.DBConnectionManager;
import com.umg.proyectofinaldb.sync.SyncService;
import com.umg.proyectofinaldb.util.FileLogger;

import javax.sql.DataSource;
import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author PC
 */
public class MainFrame extends javax.swing.JFrame {

    
    private DBConnectionManager dbManager;
    private DataSource dsSql;
    private DataSource dsOracle;
    private FileLogger fileLogger;
    private SyncService syncService;

    public MainFrame() {
        initComponents(); // generado por NetBeans GUI Builder
        dbManager = new DBConnectionManager();
        fileLogger = new FileLogger("./bitacora.txt");
        syncService = new SyncService(fileLogger);
        lblStatusSqlServer.setText("No conectado");
        lblStatusOracle1.setText("No conectado");

        // --- Botón Conectar SQL Server ---
        btnConnectSqlServer.addActionListener((ActionEvent e) -> {
            try {
                dbManager.loadFromProperties(); // carga propiedades de app.properties
                dsSql = dbManager.createSqlServerDataSource();
                lblStatusSqlServer.setText("Conectado");
                appendLog("SQL Server conectado.");
            } catch (Exception ex) {
                lblStatusSqlServer.setText("Error");
                appendLog("Error al conectar SQL Server: " + ex.getMessage());
                ex.printStackTrace();
            }
        });

        // --- Botón Conectar Oracle ---
        btnConnectOracle.addActionListener((ActionEvent e) -> {
            try {
                dbManager.loadFromProperties();
                dsOracle = dbManager.createOracleDataSource();
                lblStatusOracle1.setText("Conectado");
                appendLog("Oracle conectado.");
            } catch (Exception ex) {
                lblStatusOracle1.setText("Error");
                appendLog("Error al conectar Oracle: " + ex.getMessage());
                ex.printStackTrace();
            }
        });

        // --- Botón Sincronizar ---
        btnSync.addActionListener((ActionEvent e) -> {
            if (dsSql == null || dsOracle == null) {
                JOptionPane.showMessageDialog(this, "Conecta ambas bases primero.");
                return;
            }

            // ejecutar en background para no bloquear UI
            SwingWorker<Void, String> worker = new SwingWorker<>() {
                @Override
                protected Void doInBackground() {
                    appendLog("Iniciando sincronización...");
                    try {
                        syncService.sincronizar(dsSql, "SQLSERVER", dsOracle, "ORACLE");
                        publish("Sincronización finalizada.");
                    } catch (Exception ex) {
                        publish("Error: " + ex.getMessage());
                        ex.printStackTrace();
                    }
                    return null;
                }

                @Override
                protected void process(java.util.List<String> chunks) {
                    for (String s : chunks) appendLog(s);
                }
            };
            worker.execute();
        });
    }

    private void appendLog(String s) {
        txtLog.append(s + "\n");
    }
    /**
     * Creates new form MainFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSync = new javax.swing.JButton();
        btnConnectOracle = new javax.swing.JButton();
        btnConnectSqlServer = new javax.swing.JButton();
        lblStatusOracle1 = new javax.swing.JLabel();
        lblStatusSqlServer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnSync.setText("Sincronizacion");

        btnConnectOracle.setText("ORACLE Con");

        btnConnectSqlServer.setText("SQL Con");

        lblStatusOracle1.setBackground(new java.awt.Color(153, 153, 153));
        lblStatusOracle1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStatusSqlServer.setBackground(new java.awt.Color(153, 153, 153));
        lblStatusSqlServer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSync, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(btnConnectSqlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConnectOracle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusSqlServer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatusOracle1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConnectSqlServer)
                        .addGap(18, 18, 18)
                        .addComponent(btnConnectOracle)
                        .addGap(18, 18, 18)
                        .addComponent(btnSync))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStatusSqlServer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatusOracle1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnectOracle;
    private javax.swing.JButton btnConnectSqlServer;
    private javax.swing.JButton btnSync;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusOracle1;
    private javax.swing.JLabel lblStatusSqlServer;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
